version: '2'
services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    links:
      - mongodb
    expose:
      - "5000"
    command: "nodemon server.js"
  client_web:
    build: ./client-web
    volumes:
      - ./client-web:/app
    links:
      - server
    expose:
      - "3000"
    command: "npm start"
  mongodb:
    image: mongo
